using Salon.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Printing;
using System.Windows.Forms;

public class ReportPrinter<T>
{
    private readonly List<T> _data;
    private readonly string _title;
    private readonly List<(string Header, Func<T, string> ValueSelector, int X)> _columns;
    private readonly List<(string Label, Func<IEnumerable<T>, string> SummaryFunc)> _summaries;
    private decimal totalVat, totalDiscount, grandTotal;

    public ReportPrinter(List<T> data, string title,
        List<(string Header, Func<T,
            string> ValueSelector,
            int X)> columns,
        List<(string Label, Func<IEnumerable<T>, string> SummaryFunc)> summaries)
    {
        _data = data;
        _title = title;
        _columns = columns;
        _summaries = summaries;
    }

    public void Print()
    {
        PrintDocument printDoc = new PrintDocument();
        printDoc.PrintPage += PrintDoc_PrintPage;

        PrintPreviewDialog preview = new PrintPreviewDialog();
        preview.Document = printDoc;
        preview.WindowState = FormWindowState.Maximized;
        preview.ShowDialog();
    }

    private void PrintDoc_PrintPage(object sender, PrintPageEventArgs e)
    {
        Font font = new Font("Arial", 10);
        Font headerFont = new Font("Arial", 10, FontStyle.Bold);
        Font titleFont = new Font("Arial", 14, FontStyle.Bold);
        Font summaryFont = new Font("Arial", 12, FontStyle.Bold);
        Font footerFont = new Font("Arial", 8);

        int x = e.MarginBounds.Left;
        int y = e.MarginBounds.Top;

        // Company Header
        e.Graphics.DrawString("Hair Care Center Salon", new Font("Arial", 16, FontStyle.Bold), Brushes.Black, x, y);
        e.Graphics.DrawString("Taguig City", font, Brushes.Black, x, y + 25);
        e.Graphics.DrawString("Tel: (02) 123-4567", font, Brushes.Black, x, y + 40);
        y += 70;

        // Report Title and Metadata
        e.Graphics.DrawString(_title, titleFont, Brushes.Black, x, y);
        y += 30;
        e.Graphics.DrawString($"Printed on {DateTime.Now:MM/dd/yyyy hh:mm:ss tt}", font, Brushes.Black, x, y);
        y += 30;

        // Always draw header row once
        e.Graphics.FillRectangle(Brushes.LightGray, new Rectangle(x, y, 650, 25));
        foreach (var col in _columns)
        {
            e.Graphics.DrawString(col.Header, headerFont, Brushes.Black, col.X, y);
        }
        y += 25;

        totalVat = 0; totalDiscount = 0; grandTotal = 0;

        foreach (var item in _data)
        {
            // Alternating row shading
            if ((_data.IndexOf(item) % 2) == 1)
                e.Graphics.FillRectangle(Brushes.WhiteSmoke, new Rectangle(x, y, 650, 20));

            foreach (var col in _columns)
            {
                e.Graphics.DrawString(col.ValueSelector(item), font, Brushes.Black, col.X, y);
            }

            if (item is InvoiceServicesCart cart)
            {
                totalVat += cart.VatAmount;
                totalDiscount += cart.DiscountAmount;
                grandTotal += cart.Total_Price;
            }

            y += 20;

            if (y > e.MarginBounds.Bottom - 120)
            {
                e.HasMorePages = true;
                return;
            }
        }

        // Summary Section
        y += 20;
        e.Graphics.DrawLine(Pens.Black, x, y, x + 650, y);
        y += 10;

        e.Graphics.DrawString("Summary Totals", summaryFont, Brushes.Black, x, y);
        y += 25;

        foreach (var summary in _summaries)
        { string value = summary.SummaryFunc(_data);
            e.Graphics.DrawString(summary.Label + ":", headerFont, Brushes.Black, x, y);
            e.Graphics.DrawString(value, headerFont, Brushes.Black, x + 470, y); y += 20; }

        // Footer Branding
        y = e.MarginBounds.Bottom + 30;
        e.Graphics.DrawString("Generated by Salon Management System", footerFont, Brushes.Gray, x, y);
    }
}
