

using MaterialSkin.Controls;
using MaterialSkin.Controls;
using Salon.Controller;
using Salon.Models;
using Salon.Repository;
using Salon.Util;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
namespace Salon.ReportForm
{
    public partial class Sales_Report : MaterialForm
    {
        private PrintDocument printDoc; 
        private System.Collections.Generic.List<InvoiceServicesCart> filtered;

        public Sales_Report()
        {
            InitializeComponent();
            ThemeManager.ApplyTheme(this);

            printDoc = new PrintDocument();
            printDoc.PrintPage += printDocument1_PrintPage;

        }

        private void Sales_Report_Load(object sender, EventArgs e)
        {
           

        }

        private void printDocument1_PrintPage(object sender, PrintPageEventArgs e)
        {
            Font font = new Font("Arial", 10);
            Font headerFont = new Font("Arial", 10, FontStyle.Bold);
            Font titleFont = new Font("Arial", 14, FontStyle.Bold);
            Font summaryFont = new Font("Arial", 12, FontStyle.Bold);

            int x = e.MarginBounds.Left;
            int y = e.MarginBounds.Top;

            // Company header
            e.Graphics.DrawString("My Salon Co.", new Font("Arial", 16, FontStyle.Bold), Brushes.Black, x, y);
            e.Graphics.DrawString("123 Main St, Taguig, Metro Manila", font, Brushes.Black, x, y + 25);
            e.Graphics.DrawString("Tel: (02) 123-4567", font, Brushes.Black, x, y + 40);
            y += 70;

            // Report title and metadata
            e.Graphics.DrawString("Sales Report", titleFont, Brushes.Black, x, y);
            y += 30;
            
            y += 20;
            e.Graphics.DrawString($"Printed on {DateTime.Now}", font, Brushes.Black, x, y);
            y += 40;

            // Header row
            e.Graphics.FillRectangle(Brushes.LightGray, new Rectangle(x, y, 650, 25));
            e.Graphics.DrawString("Service", headerFont, Brushes.Black, x, y);
            e.Graphics.DrawString("Item", headerFont, Brushes.Black, x + 150, y);
            e.Graphics.DrawString("Qty", headerFont, Brushes.Black, x + 300, y);
            e.Graphics.DrawString("VAT", headerFont, Brushes.Black, x + 370, y);
            e.Graphics.DrawString("Discount", headerFont, Brushes.Black, x + 470, y);
            e.Graphics.DrawString("Total", headerFont, Brushes.Black, x + 570, y);
            y += 25;

            decimal totalVat = 0, totalDiscount = 0, grandTotal = 0;

            foreach (var item in filtered)
            {
                e.Graphics.DrawString(item.ServiceName, font, Brushes.Black, x, y);
                e.Graphics.DrawString(item.ItemName, font, Brushes.Black, x + 150, y);
                e.Graphics.DrawString(item.Quantity.ToString(), font, Brushes.Black, x + 300, y);
                e.Graphics.DrawString(item.VatAmount.ToString("F2"), font, Brushes.Black, x + 370, y);
                e.Graphics.DrawString(item.DiscountAmount.ToString("F2"), font, Brushes.Black, x + 470, y);
                e.Graphics.DrawString(item.Total_Price.ToString("F2"), font, Brushes.Black, x + 570, y);

                totalVat += item.VatAmount;
                totalDiscount += item.DiscountAmount;
                grandTotal += item.Total_Price;

                y += 20;

                if (y > e.MarginBounds.Bottom - 100)
                {
                    e.HasMorePages = true;
                    return;
                }
            }

            // Summary section
            y += 20;
            e.Graphics.DrawLine(Pens.Black, x, y, x + 650, y);
            y += 10;

            e.Graphics.DrawString("Summary Totals", summaryFont, Brushes.Black, x, y);
            y += 25;

            e.Graphics.DrawString("Total VAT:", headerFont, Brushes.Black, x + 370, y);
            e.Graphics.DrawString(totalVat.ToString("F2"), headerFont, Brushes.Black, x + 470, y);

            e.Graphics.DrawString("Total Discount:", headerFont, Brushes.Black, x + 370, y + 20);
            e.Graphics.DrawString(totalDiscount.ToString("F2"), headerFont, Brushes.Black, x + 470, y + 20);

            e.Graphics.DrawString("Grand Total:", summaryFont, Brushes.Black, x + 370, y + 40);
            e.Graphics.DrawString(grandTotal.ToString("F2"), summaryFont, Brushes.Black, x + 470, y + 40);

            // Footer
            y = e.MarginBounds.Bottom + 30;
            e.Graphics.DrawString("Generated by Salon Management System", font, Brushes.Black, x, y);
        }



        private void btn_print_Click(object sender, EventArgs e)
        {
            int offset = (1 - 1) * 25;
            var repo = new InvoiceRepository();
            var controller = new InvoiceController(repo);

            var sales_report = controller.GetSalesReportView(20, offset);

            filtered = sales_report.ToList();
            PrintPreviewDialog preview = new PrintPreviewDialog();
            preview.Document = printDoc;
            preview.ShowDialog();
            //string reportPath = Path.Combine(Application.StartupPath, "Report", "Sales_Report.rdlc");
            //var rds = new Microsoft.Reporting.WinForms.ReportDataSource("Sales_Report_dt", sales_report);
        }
    }
}
